# Generated by Django 4.2.30 on 2026-05-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, default='Gestión Inmobiliaria', max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('logo', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Perfil de Inmobiliaria',
            },
        ),
    ]
