# Generated by Django 4.2.30 on 2026-05-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_add_perfil_inmobiliaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilinmobiliaria',
            name='localidad',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
