# Generated by Django 4.2.29 on 2026-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0002_alter_historialindice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceIPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice IPC',
                'verbose_name_plural': 'Índices IPC',
                'ordering': ['anio', 'mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
