# Generated by Django 4.2.29 on 2026-04-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0003_add_indice_ipc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiceipc',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
