# Generated by Django 4.2.29 on 2026-04-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0004_fix_indice_ipc_max_digits'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceICL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nivel', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice ICL',
                'verbose_name_plural': 'Índices ICL',
                'ordering': ['anio', 'mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
