# Generated by Django 4.2.29 on 2026-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='estadomensual',
            name='unique_contrato_mes_anio',
        ),
        migrations.AddField(
            model_name='contrato',
            name='valorConceptosExtras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='aumentomensual',
            name='tipoAumento',
            field=models.CharField(choices=[('IPC', 'IPC'), ('ICL', 'ICL'), ('casa_propia', 'Casa Propia'), ('porcentaje_fijo', 'Porcentaje Fijo'), ('monto_fijo', 'Monto Fijo'), ('mora', 'Mora')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipoAumento',
            field=models.CharField(blank=True, choices=[('IPC', 'IPC'), ('ICL', 'ICL'), ('casa_propia', 'Casa Propia'), ('porcentaje_fijo', 'Porcentaje Fijo'), ('monto_fijo', 'Monto Fijo')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='estadomensual',
            unique_together={('contrato', 'mes', 'anio')},
        ),
    ]
