# Generated by Django 4.2.29 on 2026-04-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_estadomensual_unique_contrato_mes_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='incluye_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=5),
        ),
    ]
