# Generated by Django 4.2.29 on 2026-04-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_incluye_iva_contrato_porcentaje_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadomensual',
            name='aumento_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
