# Generated by Django 4.2.29 on 2026-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contrato_garante_documento_and_mora_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='direccion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipoPropiedad',
            field=models.CharField(choices=[('local', 'Local'), ('oficina', 'Oficina'), ('departamento', 'Departamento'), ('casa', 'Casa'), ('galpon', 'Galpon')], max_length=20),
        ),
    ]
