# Generated by Django 4.2.29 on 2026-04-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_contrato_direccion_alter_contrato_tipopropiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='porcentajeCasaPropia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
