# Generated by Django 4.2.29 on 2026-04-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_add_porcentaje_casa_propia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='garanteDocumentoArchivo',
            field=models.FileField(blank=True, null=True, upload_to='garantes/'),
        ),
    ]
