# Generated by Django 4.2.29 on 2026-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_alter_contrato_garantedocumentoarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='garantes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
