# Generated by Django 4.2.29 on 2026-04-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_add_garantes_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento (ej: A, B, C, etc)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='piso',
            field=models.CharField(blank=True, help_text='Número de piso (ej: 4, PB, etc)', max_length=10, null=True),
        ),
    ]
