# Generated by Django 4.2.29 on 2026-04-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_contrato_departamento_contrato_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipoPropiedad',
            field=models.CharField(choices=[('local', 'Local'), ('oficina', 'Oficina'), ('departamento', 'Departamento'), ('casa', 'Casa'), ('galpon', 'Galpon'), ('cochera', 'Cochera')], max_length=20),
        ),
    ]
