# Generated by Django 4.2.29 on 2026-04-29 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0011_add_cochera_tipo_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL),
        ),
    ]
