# Generated by Django 4.2.29 on 2026-04-29 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0013_assign_existing_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL),
        ),
    ]
