# Generated by Django 4.2.29 on 2026-05-04 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0014_make_usuario_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='contratoPdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='contratos/pdf/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='garanteDocumentoArchivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='garantes/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL),
        ),
    ]
