# Generated by Django 4.2.29 on 2026-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_alter_contrato_contratopdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contratoImagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
