# Generated by Django 4.2.30 on 2026-05-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_add_contrato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='emos_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto para EMOS', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='municipalidad_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto para Municipalidad', max_digits=12, null=True),
        ),
    ]
