# Generated by Django 4.2.29 on 2026-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_contrato_emos_monto_contrato_municipalidad_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='emos_monto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='municipalidad_monto',
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratoAnexos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratoImagenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
