# Generated by Django 4.2.30 on 2026-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_remove_contrato_emos_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aumentomensual',
            name='tipoAumento',
            field=models.CharField(choices=[('IPC', 'IPC'), ('ICL', 'ICL'), ('casa_propia', 'Casa Propia'), ('porcentaje_fijo', 'Porcentaje Fijo'), ('monto_fijo', 'Monto Fijo'), ('mora', 'Mora')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fechaFin',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fechaInicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='monedaMensual',
            field=models.CharField(db_index=True, default='ARS', max_length=10),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipoPropiedad',
            field=models.CharField(choices=[('local', 'Local'), ('oficina', 'Oficina'), ('departamento', 'Departamento'), ('casa', 'Casa'), ('galpon', 'Galpon'), ('cochera', 'Cochera')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='estadomensual',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['usuario', 'eliminado'], name='contrato_usuario_eliminado_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fechaInicio', 'fechaFin'], name='contrato_fechas_idx'),
        ),
    ]
