# Generated by Django 4.2.30 on 2026-05-27 01:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadomensual',
            name='comprobante_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estadomensual',
            name='comprobante_revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadomensual',
            name='comprobante_subidoEn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadomensual',
            name='comprobante_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PortalInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Portal Inquilino',
                'verbose_name_plural': 'Portales Inquilinos',
            },
        ),
    ]
